# Generated by Django 3.2.5 on 2021-09-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_venda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro NF-e'), ('ver_dashboard', 'Pode visualizar o dashdoard'), ('permissão3', 'Permissão3'))},
        ),
    ]
