# Generated by Django 3.2.5 on 2021-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaExistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'MinhaTabela2',
            },
        ),
    ]
