# Generated by Django 3.2.5 on 2021-12-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_tabelaexistente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tabelaexistente',
            table='MinhaTabela2',
        ),
    ]
